pipeline:
  gcc6:
    image: debian:stretch-slim
    pull: true
    environment:
      - LANG=C.utf8
      - CXX=g++-6
      - CXXFLAGS=-pipe -O2
    commands:
      - rm /etc/apt/apt.conf.d/docker-clean
      - apt-get update -q
      - apt-get install -qy g++ cmake pkg-config
      - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev
      - apt-get install -qy dpkg-dev rpm file wget
      - gpg --import /var/autosign_gpg.key
      - rm -rf build && mkdir -p build && cd build
      - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
      - make VERBOSE=1
      - make install DESTDIR=install
      - make package
      - cmake -DWITH_DEB=ON ..
      - make package
      - cmake -DWITH_DEB=OFF -DWITH_RPM=ON ..
      - make package
      - gpg --verbose --detach-sign *.tar.gz
      - gpg --verbose --detach-sign *.deb
      - gpg --verbose --detach-sign *.rpm
    volumes:
      - /var/cache/debian-package-cache:/var/cache/apt/archives
      - /home/tastytea/misc/autosign_gpg.key:/var/autosign_gpg.key

  gcc7:
    image: debian:stretch-slim
    pull: true
    when:
      event: [push, pull_request]
    environment:
      - LANG=C.utf8
      - CXX=g++-7
      - CXXFLAGS=-pipe -O2
    commands:
      - rm /etc/apt/apt.conf.d/docker-clean
      - apt-get update -q
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/backports.list
      - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      - apt-get install -qy gnupg
      - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
      - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
      - apt-get update -q
      - apt-get install -qy -t xenial g++-7
      - apt-get install -qy cmake pkg-config
      - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
    volumes:
      - /var/cache/debian-package-cache:/var/cache/apt/archives

  gcc8:
    image: debian:stretch-slim
    pull: true
    when:
      event: [push, pull_request]
    environment:
      - LANG=C.utf8
      - CXX=g++-8
      - CXXFLAGS=-pipe -O2
    commands:
      - rm /etc/apt/apt.conf.d/docker-clean
      - apt-get update -q
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/backports.list
      - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      - apt-get install -qy gnupg
      - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
      - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
      - apt-get update -q
      - apt-get install -qy -t xenial g++-8
      - apt-get install -qy cmake pkg-config
      - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
    volumes:
      - /var/cache/debian-package-cache:/var/cache/apt/archives

  clang3:
    image: debian:stretch-slim
    pull: true
    when:
      event: [push, pull_request]
    environment:
      - LANG=C.utf8
      - CXX=clang++
      - CXXFLAGS=-pipe -O2
    commands:
      - rm /etc/apt/apt.conf.d/docker-clean
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/backports.list
      - apt-get update -q
      - apt-get install -qy clang cmake pkg-config
      - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
    volumes:
      - /var/cache/debian-package-cache:/var/cache/apt/archives

  clang5:
    image: debian:stretch-slim
    pull: true
    when:
      event: [push, pull_request]
    environment:
      - LANG=C.utf8
      - CXX=clang++-5.0
      - CXXFLAGS=-pipe -O2
    commands:
      - rm /etc/apt/apt.conf.d/docker-clean
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/stretch.list
      - apt-get update -q
      - apt-get install -qy -t stretch-backports clang-5.0
      - apt-get install -qy cmake pkg-config
      - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
    volumes:
      - /var/cache/debian-package-cache:/var/cache/apt/archives

  clang6:
    image: debian:stretch-slim
    pull: true
    when:
      event: [push, pull_request]
    environment:
      - LANG=C.utf8
      - CXX=clang++-6.0
      - CXXFLAGS=-pipe -O2
    commands:
      - rm /etc/apt/apt.conf.d/docker-clean
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/stretch.list
      - apt-get update -q
      - apt-get install -qy -t stretch-backports clang-6.0
      - apt-get install -qy cmake pkg-config
      - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
    volumes:
      - /var/cache/debian-package-cache:/var/cache/apt/archives

  prepare_release:
    image: debian:jessie-slim
    pull: true
    when:
      event: tag
    commands:
      - cp -v build/whyblocked-${DRONE_TAG}_x86_64.tar.gz .
      - cp -v build/whyblocked-${DRONE_TAG}_x86_64.tar.gz.sig .
      - cp -v build/whyblocked_${DRONE_TAG}-0_amd64.deb .
      - cp -v build/whyblocked_${DRONE_TAG}-0_amd64.deb.sig .
      - cp -v build/whyblocked-${DRONE_TAG}-0.x86_64.rpm .
      - cp -v build/whyblocked-${DRONE_TAG}-0.x86_64.rpm.sig .
  gitea_release:
    image: plugins/gitea-release
    pull: true
    when:
      event: tag
    base_url: https://schlomp.space
    secrets: [ gitea_token ]
    title: ${DRONE_TAG}
    prerelease: true
    files:
      - whyblocked-${DRONE_TAG}_x86_64.tar.gz
      - whyblocked-${DRONE_TAG}_x86_64.tar.gz.sig
      - whyblocked_${DRONE_TAG}-0_amd64.deb
      - whyblocked_${DRONE_TAG}-0_amd64.deb.sig
      - whyblocked-${DRONE_TAG}-0.x86_64.rpm
      - whyblocked-${DRONE_TAG}-0.x86_64.rpm.sig
    checksum:
      - sha256
      - sha512

  notify:
    image: drillster/drone-email
    pull: true
    host: cryptoparty-celle.de
    secrets: [ email_username, email_password ]
    from: drone@tzend.de
    when:
      status: [ changed, failure ]
