pipeline:
  gcc8:
    image: gcc:8
    pull: true
    commands:
      - apt-get update -q
      - apt-get install -qy cmake libvsqlitepp-dev libboost-all-dev libxdg-basedir-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
  gcc7:
    image: gcc:7
    pull: true
    commands:
      - apt-get update -q
      - apt-get install -qy cmake libvsqlitepp-dev libboost-all-dev libxdg-basedir-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
  gcc6:
    image: gcc:6
    pull: true
    commands:
      - apt-get update -q
      - apt-get install -qy cmake libvsqlitepp-dev libboost-all-dev libxdg-basedir-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
  gcc5:
    image: gcc:5
    pull: true
    commands:
      - apt-get update -q
      - apt-get install -qy cmake libvsqlitepp-dev libboost-all-dev libxdg-basedir-dev
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
  notify:
    image: drillster/drone-email
    pull: true
    host: cryptoparty-celle.de
    secrets: [ email_username, email_password ]
    from: drone@tzend.de
    when:
      status: [ changed, failure ]
