kind: pipeline
name: build x86_64

volumes:
- name: debian-package-cache
  host:
    path: /var/cache/debian-package-cache

trigger:
  event:
    exclude:
    - tag

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule init
    - git submodule update --recursive

- name: gcc6
  image: ubuntu:xenial
  pull: always
  environment:
    CXX: g++-6
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
  - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
  - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
  - rm /var/cache/apt/archives/lock
  - apt-get update -q
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy g++-6 cmake pkg-config
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev asciidoc
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make VERBOSE=1
  - make install DESTDIR=install
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: gcc9
  image: debian:stretch-slim
  pull: always
  environment:
    CXX: g++-9
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - rm /var/cache/apt/archives/lock
  - apt-get update -q
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/backports.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy gnupg
  - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
  - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
  - rm /var/cache/apt/archives/lock
  - apt-get update -q
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy -t xenial g++-9
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy cmake pkg-config
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev asciidoc
  - rm -rf build && mkdir -p build && cd build
  - cmake ..
  - make VERBOSE=1
  - make install DESTDIR=install
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: clang3
  image: debian:stretch-slim
  pull: always
  environment:
    CXX: clang++
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/backports.list
  - rm /var/cache/apt/archives/lock
  - apt-get update -q
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy clang cmake pkg-config
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev asciidoc
  - rm -rf build && mkdir -p build && cd build
  - cmake ..
  - make VERBOSE=1
  - make install DESTDIR=install
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: clang6
  image: debian:stretch-slim
  pull: always
  environment:
    CXX: clang++-6.0
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/stretch.list
  - rm /var/cache/apt/archives/lock
  - apt-get update -q
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy -t stretch-backports clang-6.0
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy cmake pkg-config
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev asciidoc
  - rm -rf build && mkdir -p build && cd build
  - cmake ..
  - make VERBOSE=1
  - make install DESTDIR=install
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: notify
  image: drillster/drone-email
  pull: always
  settings:
    host: cryptoparty-celle.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
    from: drone@tzend.de
  when:
    status: [ changed, failure ]

---
kind: pipeline
name: packages x86_64

volumes:
- name: debian-package-cache
  host:
    path: /var/cache/debian-package-cache
- name: gpg-key
  host:
    path: /var/autosign_gpg.key

trigger:
  event:
    - tag

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule init
    - git submodule update --recursive

- name: gcc6
  image: ubuntu:xenial
  pull: always
  environment:
    CXX: g++-6
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
  - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
  - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
  - rm /var/cache/apt/archives/lock
  - apt-get update -q
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy g++-6 cmake pkg-config
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy libvsqlitepp-dev libboost-dev libxdg-basedir-dev qt5-default qttools5-dev-tools qttools5-dev libconfig++-dev asciidoc
  - rm /var/cache/apt/archives/lock
  - apt-get install -qy dpkg-dev rpm file wget
  - gpg --import /var/autosign_gpg.key
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make VERBOSE=1
  - make install DESTDIR=install
  - make package
  - cmake -DWITH_DEB=ON ..
  - make package
  - cmake -DWITH_DEB=OFF -DWITH_RPM=ON ..
  - make package
  - gpg --verbose --detach-sign *.tar.gz
  - gpg --verbose --detach-sign *.deb
  - gpg --verbose --detach-sign *.rpm
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives
  - name: gpg-key
    path: /var/autosign_gpg.key

- name: prepare_release
  image: ubuntu:xenial
  pull: always
  commands:
  - cp -v build/whyblocked-${DRONE_TAG}_x86_64.tar.gz .
  - cp -v build/whyblocked-${DRONE_TAG}_x86_64.tar.gz.sig .
  - cp -v build/whyblocked_${DRONE_TAG}-0_amd64.deb .
  - cp -v build/whyblocked_${DRONE_TAG}-0_amd64.deb.sig .
  - cp -v build/whyblocked-${DRONE_TAG}-0.x86_64.rpm .
  - cp -v build/whyblocked-${DRONE_TAG}-0.x86_64.rpm.sig .

- name: release
  image: plugins/gitea-release
  pull: always
  settings:
    base_url: https://schlomp.space
    api_key:
      from_secret: gitea_token
    title: ${DRONE_TAG}
    prerelease: true
    files:
      - whyblocked-${DRONE_TAG}_x86_64.tar.gz
      - whyblocked-${DRONE_TAG}_x86_64.tar.gz.sig
      - whyblocked_${DRONE_TAG}-0_amd64.deb
      - whyblocked_${DRONE_TAG}-0_amd64.deb.sig
      - whyblocked-${DRONE_TAG}-0.x86_64.rpm
      - whyblocked-${DRONE_TAG}-0.x86_64.rpm.sig
    checksum:
      - sha256
      - sha512

- name: notify
  image: drillster/drone-email
  pull: always
  settings:
    host: cryptoparty-celle.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
    from: drone@tzend.de
  when:
    status: [ changed, failure ]
